export const TERMINAL_STATUSES = [
  'JOINED',
  'REJECTED',
  'DECLINED',
  'WITHDRAWN',
  'NO_SHOW',
  'CLOSED',
] as const;

export const POST_HOD_STATUSES = [
  'PENDING_HR_HEAD_APPROVAL',
  'SENT_BACK_BY_HR_HEAD',
  'APPROVED',
  'OFFER_RELEASED',
  'ACCEPTED',
  'ONBOARDING_IN_PROGRESS',
  'JOINED',
  'DECLINED',
  'WITHDRAWN',
  'CLOSED',
] as const;

export const POST_ACCEPTANCE_STATUSES = [
  'ACCEPTED',
  'ONBOARDING_IN_PROGRESS',
  'JOINED',
] as const;

export const ACTIVE_STATUSES = [
  'DRAFT',
  'PENDING_TA_APPROVAL',
  'SENT_BACK_BY_TA',
  'PENDING_HOD_APPROVAL',
  'SENT_BACK_BY_HOD',
  'PENDING_HR_HEAD_APPROVAL',
  'SENT_BACK_BY_HR_HEAD',
  'APPROVED',
  'OFFER_RELEASED',
  'ACCEPTED',
  'ONBOARDING_IN_PROGRESS',
] as const;

// Valid state transitions
export const VALID_TRANSITIONS: Record<string, string[]> = {
  DRAFT: ['PENDING_TA_APPROVAL'],
  PENDING_TA_APPROVAL: ['SENT_BACK_BY_TA', 'REJECTED', 'PENDING_HOD_APPROVAL'],
  SENT_BACK_BY_TA: ['PENDING_TA_APPROVAL'],
  PENDING_HOD_APPROVAL: ['SENT_BACK_BY_HOD', 'REJECTED', 'PENDING_HR_HEAD_APPROVAL'],
  SENT_BACK_BY_HOD: ['PENDING_TA_APPROVAL'],
  PENDING_HR_HEAD_APPROVAL: ['SENT_BACK_BY_HR_HEAD', 'REJECTED', 'APPROVED'],
  SENT_BACK_BY_HR_HEAD: ['PENDING_TA_APPROVAL'],
  APPROVED: ['OFFER_RELEASED'],
  OFFER_RELEASED: ['ACCEPTED', 'DECLINED', 'WITHDRAWN', 'CLOSED'],
  ACCEPTED: ['ONBOARDING_IN_PROGRESS'],
  ONBOARDING_IN_PROGRESS: ['JOINED', 'NO_SHOW'],
};
